apiVersion: v1
kind: Service
metadata:
  namespace: development
  name: database-service
spec:
  selector:
    app: api-service-database
    tier: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  namespace: development
  name: api-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    app: api-service-api
    tier: api
---

